### PR TITLE
fix a few cases of “Missing } inserted”:

### PR DESCRIPTION
**Pull request by mirabilos**
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920459
 * https://github.com/tabu-fixed/tabu/issues/1

An immediate review would be *massively* welcome; we’re just before a stable Debian release and would like to have a fixed tabu included… thanks in advance!

Cc @norbusan since we’ll likely need to apply this patch to fix several FTBFS in multiple packages…

### CODE REVIEW

**Comment by u-fischer** [comment]
well it seems to get rid of some of the errors from examples in issue #1. And the \color@begingroup seems to match the \color@endgroup in `\tabu@endpboxmeasure`. 

But I wonder why the \color@endgroup was added, and if an additional begingroup leads to a regression.

**Comment by mirabilos** [comment]
Ulrike Fischer dixit:

>well it seems to get rid of some of the errors from examples in issue #1.

Yes, it does. That’s really all about this… ;)

>And the \color@begingroup seems to match the \color@endgroup in
>`\tabu@endpboxmeasure`.
>
>But I wonder why the \color@endgroup was added, and if an additional
>begingroup leads to a regression.

Sorry, I don’t have answers for you for that ☹ my Teχ skills aren’t
t̲h̲a̲t̲ great… see also the messages starting around:
 https://chat.stackexchange.com/transcript/message/49187199#49187199

**Comment by norbusan** [comment]
> Cc @norbusan since we’ll likely need to apply this patch to fix several FTBFS in multiple packages…

@mirabilos Might all be nice and shiny, but I cannot upload, ftp-masters don't answer after initial response, Debian has to live with the mess that it created. Pity.

**Comment by FrankMittelbach** [comment]
I used the code thanks, but done some parts slightly differently.

**Pull request closed without merging**
